
services:
  backend:
    build:
      context: ./backend/NotesApiMongo
    ports:
      - "5037:5037"
    environment:
      - ASPNETCORE_URLS=http://+:5037
      - Jwt__Key="MyUltraSuperLongSecretJWTKey1234567890!!!=="
      - Jwt__Issuer=NotesApp
      - Jwt__Audience=NotesUsers
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
